#!/bin/bash
if [ -z "$PYFILE" ]; then
    echo "Error: PYFILE environment variable not set"
    exit 1
fi

if [ ! -f "$PYFILE" ]; then
    echo "Error: $PYFILE does not exist or is not a regular file"
    exit 1
fi

pyc_file="${PYFILE}c"
python3 -m py_compile "$PYFILE" && mv "${PYFILE}c" "$pyc_file"
